from colas import *
cola_1=cola_secuencial(4)
cola_2=cola_enlazada()
cola_2.insertar(1)
cola_2.insertar(2)
cola_2.insertar(3)
cola_2.insertar(4)
cola_2.recorrer()
cola_2.suprimir_todo()
cola_2.recorrer()