SECRET_KEY='DGgd203302'
SQLALCHEMY_DATABASE_URI='sqlite:///C:/Users/Lolma/Documents/Codigos/Python/POO/PRACTICOS/Practico Flask/datos.sqlite3'
SQLALCHEMY_TRACK_MODIFICATIONS= False
SEND_FILE_MAX_AGE_DEFAULT=0